figmaの画面を作成 (ログイン画面の作成)
hirokisato712/next-storybook-for-beginners pull request #6
Opened 2024-07-08 10:41 UTC by hirokisato712

- [ ]  app/auth/login/login.tsx の文言とレイアウトをFigmaにあるものと同じものに変更
- [ ]  app/auth/login/login.tsx を編集
- [ ]  ダッシュボードページを参考にコンポーネントを作成

キャプチャー
![スクリーンショット 2024-07-08 193958](https://github.com/hirokisato712/next-storybook-for-beginners/assets/174312391/072d8b27-0309-4e13-9823-e2fc46074402)

2024-07-08 12:41 UTC, fox-Taisei-Nakamura requested changes

2024-07-08 12:41 UTC, fox-Taisei-Nakamura commented on app/auth/login/login.tsx
> +        style={{
tailwindの指定方法にしてください

2024-07-09 02:58 UTC, hirokisato712 commented on app/auth/login/login.tsx
> +        style={{
修正しました。ご確認お願い致します。

2024-07-09 03:12 UTC, fox-Taisei-Nakamura approved these changes

2024-07-09 03:13 UTC, merged