figmaの画面を作成(社員・協力会社の画面を作成)
hirokisato712/next-storybook-for-beginners pull request #8
Opened 2024-07-09 10:58 UTC by hirokisato712

- [x] order画面を参考に社員一覧が表示されるテーブルを作成
- [x] 必要な文言を追加
- [x] MUIを使ってレイアウトを調整
- [x] 表示を確認
![スクリーンショット 2024-07-09 194856](https://github.com/hirokisato712/next-storybook-for-beginners/assets/174312391/e5fcb3e5-9a06-403c-af15-b59fd05dbc01)
![スクリーンショット 2024-07-09 194921](https://github.com/hirokisato712/next-storybook-for-beginners/assets/174312391/9dfa76ab-459a-42fd-b50d-99ebee749bb1)

2024-07-09 11:13 UTC, fox-Taisei-Nakamura requested changes

2024-07-09 11:13 UTC, fox-Taisei-Nakamura commented on app/dashboard/types.ts
> +export interface ChartData {
以下不要なので削除してください

2024-07-09 11:13 UTC, fox-Taisei-Nakamura commented on app/employees/employees.stories.tsx
> +        id: 2,
id系は一意なので、連番にしてください

2024-07-10 05:50 UTC, hirokisato712 commented on app/employees/employees.stories.tsx
> +        id: 2,
storiesのIDは連番に変えました。
中身もAPIに対応するように変更しました。

2024-07-10 05:50 UTC, hirokisato712 commented on app/dashboard/types.ts
> +export interface ChartData {
不要な部分を削除しました

2024-07-10 06:25 UTC, fox-Taisei-Nakamura requested changes

2024-07-10 06:25 UTC, fox-Taisei-Nakamura commented on app/dashboard/dashboard.tsx
> +  console.log(order);
不要なら削除してください

2024-07-10 06:25 UTC, fox-Taisei-Nakamura commented on app/dashboard/page.tsx
> +  console.log(order);
不要なら削除してください

2024-07-10 06:25 UTC, fox-Taisei-Nakamura commented on app/employees/employees.tsx
> +                      <Avatar sx={{ bgcolor: row.color }}>{row.initial}</Avatar>
`sx=`はMUIでの記載のため、tailwindの記載で書いてください

2024-07-10 06:25 UTC, fox-Taisei-Nakamura commented on app/employees/page.tsx
> +  console.log(employees);
不要なら削除してください
次のタスク等で必要な場合は、コメントを追記してください

2024-07-10 09:05 UTC, hirokisato712 commented on app/employees/page.tsx
> +  console.log(employees);
削除しました。

2024-07-10 09:05 UTC, hirokisato712 commented on app/dashboard/page.tsx
> +  console.log(order);
削除しました。

2024-07-10 09:05 UTC, hirokisato712 commented on app/dashboard/dashboard.tsx
> +  console.log(order);
削除しました。

2024-07-10 09:28 UTC, fox-Taisei-Nakamura approved these changes

2024-07-10 09:31 UTC, merged